In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pyxclib.xclib.data import data_utils

#Installing pyxclib in order to work with loading txt datasets and also going to MLBD_Project folder

In [2]:
!pip install xclib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [36]:
#!git clone https://github.com/kunaldahiya/pyxclib.git

Cloning into 'pyxclib'...
remote: Enumerating objects: 1214, done.
remote: Counting objects: 100% (305/305), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 1214 (delta 216), reused 279 (delta 213), pack-reused 909
Receiving objects: 100% (1214/1214), 7.61 MiB | 7.74 MiB/s, done.
Resolving deltas: 100% (707/707), done.


In [3]:
cd /content/drive/MyDrive/MLBD_Project

/content/drive/MyDrive/MLBD_Project


In [10]:
#!unzip Amazon670K.zip

Archive:  Amazon670K.zip
   creating: Amazon670K.bow/
  inflating: Amazon670K.bow/test.txt  
  inflating: Amazon670K.bow/train.txt  
  inflating: Amazon670K.bow/Yf.txt   
  inflating: Amazon670K.bow/Xf.txt   


In [26]:
#!unzip Bibtex.zip

Archive:  Bibtex.zip
  inflating: Bibtex/Bibtex_data.txt  
  inflating: Bibtex/bibtex_trSplit.txt  
  inflating: Bibtex/bibtex_tstSplit.txt  


In [37]:
#cd pyxclib

/content/drive/MyDrive/MLBD_Project/pyxclib


In [38]:
#!python3 setup.py install --user

running install
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating xclib.egg-info
writing xclib.egg-info/PKG-INFO
writing dependency_links to xclib.egg-info/dependency_links.txt
writing requirements to xclib.egg-info/requires.txt
writing top-level names to xclib.egg-info/top_level.txt
writing manifest file 'xclib.egg-info/SOURCES.txt'
reading manifest file 'xclib.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'xclib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating buil

#Amazon670K BOW Dataset (although loaded, but way too large to work on)

In [5]:
# Read file with features and labels (old format from XMLRepo)
features, labels, num_samples, num_features, num_labels = data_utils.read_data('Amazon670K.bow/train.txt')

# Read sparse file (see docstring for more)
# header can be set to false (if required)
#labels = data_utils.read_sparse_file('trn_X_Xf.txt', header=True)

# Write sparse file (with header)
#data_utils.write_sparse_file(labels, "labels.txt")

In [6]:
num_samples, num_features, num_labels

(490449, 135909, 670091)

In [14]:
features[0,:].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [15]:
features[0,:].toarray().shape

(1, 135909)

In [18]:
labels[0,:].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
labels[0,:].toarray().shape

(1, 670091)

In [20]:
np.unique(features[0,:].toarray())

array([ 0.      ,  1.58496 ,  2.      ,  2.32193 ,  2.58496 ,  2.80735 ,
        3.      ,  3.16993 ,  3.32193 ,  3.45943 ,  4.24793 ,  4.32193 ,
        4.45943 ,  4.64386 ,  4.75489 ,  5.08746 ,  5.2854  ,  5.45943 ,
        5.58496 ,  5.61471 ,  5.72792 ,  5.80735 ,  6.      ,  6.02237 ,
        6.14975 ,  6.16993 ,  6.33985 ,  6.80735 ,  6.87036 ,  7.33985 ,
        7.35755 ,  7.3837  ,  7.42626 ,  8.67948 ,  8.86109 ,  9.02791 ,
        9.03067 ,  9.55267 ,  9.58496 ,  9.70908 ,  9.97154 , 10.0634  ,
       10.85253 , 10.92035 , 11.15165 , 11.60964 , 12.32446 , 12.45198 ,
       16.53957 , 25.5541  , 28.21928 , 47.89735 , 62.444221, 68.933067,
       72.599037])

In [21]:
np.unique(labels[0,:].toarray())

array([0., 1.], dtype=float32)